@WebApi_HostAddress = https://localhost:7089
@days = 3

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_HostAddress}}/weatherforecast/{{days}}
Accept: application/json
